security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: /logout
                target: /
                enable_csrf: false  # (désactivé pour test)

    access_control:
        # Admin uniquement pour la page /register
        - { path: ^/register, roles: ROLE_ADMIN }
        - { path: ^/gestion, roles: ROLE_ADMIN }


        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
